from langchain.messages import HumanMessage, AIMessage, ToolMessage

response = {'messages': [HumanMessage(content='query = Answer about TCS policies?', additional_kwargs={}, response_metadata={}, id='cb0b51a1-96b5-4200-9551-9ea358aaf7f0'),
              AIMessage(content='', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 20, 'prompt_tokens': 1274, 'total_tokens': 1294, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_b547601dbd', 'id': 'chatcmpl-CgE1FqQgMdO09rKPmIscvmWzYkouc', 'service_tier': 'default', 'finish_reason': 'tool_calls', 'logprobs': None}, id='lc_run--f6ec7502-9826-4b84-bd27-51c6d21a41b7-0', tool_calls=[{'name': 'retreive_augment_context', 'args': {'query': 'TCS policies'}, 'id': 'call_gXnF0ShTtQbZSwsMMm6Hm8co', 'type': 'tool_call'}], usage_metadata={'input_tokens': 1274, 'output_tokens': 20, 'total_tokens': 1294, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}),
              ToolMessage(content='TCS policies : TCS has very strict policies about personal information', name='retreive_augment_context', id='7a075071-6832-4d9d-b015-41b1f315f3a1', tool_call_id='call_gXnF0ShTtQbZSwsMMm6Hm8co'),
              AIMessage(content='', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 11, 'prompt_tokens': 1319, 'total_tokens': 1330, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 1152}}, 'model_provider': 'openai', 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_b547601dbd', 'id': 'chatcmpl-CgE1Hied1asmJGvT2f010SG6Dui7N', 'service_tier': 'default', 'finish_reason': 'tool_calls', 'logprobs': None}, id='lc_run--5c4f1f7d-8fcd-468e-b750-e5c49a16301f-0', tool_calls=[{'name': 'generate_respond', 'args': {}, 'id': 'call_JqB7hXTUnBvfjT2ki9JLE2xF', 'type': 'tool_call'}], usage_metadata={'input_tokens': 1319, 'output_tokens': 11, 'total_tokens': 1330, 'input_token_details': {'audio': 0, 'cache_read': 1152}, 'output_token_details': {'audio': 0, 'reasoning': 0}}),
              ToolMessage(content='TCS has very strict policies about personal information', name='generate_respond', id='c47d7738-f565-4f7d-bab1-e50071a89dea', tool_call_id='call_JqB7hXTUnBvfjT2ki9JLE2xF'),
              AIMessage(content='TCS has very strict policies about personal information.', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 11, 'prompt_tokens': 1348, 'total_tokens': 1359, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_b547601dbd', 'id': 'chatcmpl-CgE1IZ7DrMHsGW2rYxP8HsZmxVA8A', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--e8194ed7-f1dc-41f5-bd73-d050d429976b-0', usage_metadata={'input_tokens': 1348, 'output_tokens': 11, 'total_tokens': 1359, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})]}


print(response['messages'][-1].content)